### ISSUE TITLE
Feature Request (Synology)

### ISSUE THREAD

**Issue by ziegwald** [jamesmstone/flickr-uploadr#1]
Hi, if possible, can you make a python script with new new oauth based on this one: https://github.com/trickortweak/flickr-uploader/blob/master/uploadr.py

I don't think it will be updated, so it would be great if you can implement the new oauth for the script.

**Comment by jamesmstone** [comment]
Hey there :)
Unfortunately, I'm pretty busy at the moment, so no promises.

However, after having a quick look at their code, I don't imagine it would be too hard to integrate the this with Synology. Potentially, this tool already even has all the features you need!

What are the requirements for getting this to run on a Synology device. I don't have one

**Comment by ziegwald** [comment]
Basically, it only needs python 2.7, API key, and working token. The script I posted can automatically creates "Sets" based on the folder name which is really great, it uses the old auth method which is not working anymore though..

**Comment by jamesmstone** [comment]
This might help you more https://github.com/alfem/synology-flickr-folder-uploader
