### ISSUE TITLE
verifier must be unicode text type

### ISSUE THREAD

**Issue by lapo-luchini** [jamesmstone/flickr-uploadr#2]
Sorry, I don't know much about Python, but:

```
Traceback (most recent call last):
  File "upload.py", line 32, in <module>
    print(flickr.get_access_token(verifier))
  File "/home/lapo/.local/lib/python2.7/site-packages/flickrapi/core.py", line 666, in get_access_token
    self.flickr_oauth.verifier = verifier
  File "/home/lapo/.local/lib/python2.7/site-packages/flickrapi/auth.py", line 209, in verifier
    assert isinstance(new_verifier, six.text_type), 'verifier must be unicode text type'
AssertionError: verifier must be unicode text type
```

**Comment by lapo-luchini** [comment]
Mhh, I might have solved that with:

```
-    verifier = str(input('Verifier code: '))
+    verifier = unicode(str(input('Verifier code: ')))
```

but it still fails with:

```
No handlers could be found for logger "flickrapi.auth.OAuthFlickrInterface"
```

**Comment by jamesmstone** [comment]
hmm interesting,  are you using this as a python script, or running it though docker?

**Comment by lapo-luchini** [comment]
Directly in Python 2.7.

**Comment by jamesmstone** [comment]
This is designed to be run in a Docker container.
However there is no reason why it shouldn't work straight with python. However it uses python 3

**Comment by lapo-luchini** [comment]
Whops, I didn't notice, thanks for the heads up.
Anyways, I used the occasion to try and write my own uploader in NodeJS (an environment I know way better than Python), also for educational reasons. ;)
